import { PatientRecord } from '@/types'

// Generate realistic mock data for the dental dashboard
export const mockPatientData: PatientRecord[] = [
  {
    timestamp: '2024-01-15T10:30:00Z',
    insurancecarrier: 'Delta Dental',
    offices: 'Downtown Dental Center',
    patientname: 'John Smith',
    paidamount: 850,
    claimstatus: 'Paid',
    typeofinteraction: 'Root Canal',
    patientdob: '1985-03-12',
    dos: '2024-01-10',
    productivityamount: 850,
    missingdocsorinformation: '',
    howweproceeded: 'Claim submitted electronically',
    escalatedto: '',
    commentsreasons: 'Routine procedure, no complications',
    emailaddress: 'john.smith@email.com',
    status: 'Completed',
    timestampbyinteraction: '2024-01-15T10:30:00Z'
  },
  {
    timestamp: '2024-01-15T11:45:00Z',
    insurancecarrier: 'BlueCross BlueShield',
    offices: 'Westside Family Dental',
    patientname: 'Sarah Johnson',
    paidamount: 450,
    claimstatus: 'Pending',
    typeofinteraction: 'Cleaning',
    patientdob: '1992-07-20',
    dos: '2024-01-12',
    productivityamount: 450,
    missingdocsorinformation: 'Missing pre-authorization',
    howweproceeded: 'Contacted insurance for authorization',
    escalatedto: 'Insurance Specialist',
    commentsreasons: 'Waiting for pre-auth approval',
    emailaddress: 'sarah.j@email.com',
    status: 'In Progress',
    timestampbyinteraction: '2024-01-15T11:45:00Z'
  },
  {
    timestamp: '2024-01-15T14:20:00Z',
    insurancecarrier: 'Aetna',
    offices: 'North Park Dental',
    patientname: 'Michael Brown',
    paidamount: 1200,
    claimstatus: 'Paid',
    typeofinteraction: 'Crown Placement',
    patientdob: '1978-11-05',
    dos: '2024-01-08',
    productivityamount: 1200,
    missingdocsorinformation: '',
    howweproceeded: 'Standard claim processing',
    escalatedto: '',
    commentsreasons: 'Premium restoration completed',
    emailaddress: 'mbrown@email.com',
    status: 'Completed',
    timestampbyinteraction: '2024-01-15T14:20:00Z'
  },
  {
    timestamp: '2024-01-15T15:10:00Z',
    insurancecarrier: 'Cigna',
    offices: 'Downtown Dental Center',
    patientname: 'Emily Davis',
    paidamount: 0,
    claimstatus: 'Denied',
    typeofinteraction: 'Whitening Treatment',
    patientdob: '1995-02-14',
    dos: '2024-01-11',
    productivityamount: 300,
    missingdocsorinformation: '',
    howweproceeded: 'Appeal submitted',
    escalatedto: 'Claims Manager',
    commentsreasons: 'Cosmetic procedure not covered',
    emailaddress: 'emily.davis@email.com',
    status: 'Appeal',
    timestampbyinteraction: '2024-01-15T15:10:00Z'
  },
  {
    timestamp: '2024-01-15T16:30:00Z',
    insurancecarrier: 'MetLife',
    offices: 'Eastside Dental',
    patientname: 'Robert Wilson',
    paidamount: 650,
    claimstatus: 'Paid',
    typeofinteraction: 'Filling',
    patientdob: '1988-09-30',
    dos: '2024-01-13',
    productivityamount: 650,
    missingdocsorinformation: '',
    howweproceeded: 'Electronic submission',
    escalatedto: '',
    commentsreasons: 'Composite filling, posterior tooth',
    emailaddress: 'rwilson@email.com',
    status: 'Completed',
    timestampbyinteraction: '2024-01-15T16:30:00Z'
  },
  {
    timestamp: '2024-01-16T09:15:00Z',
    insurancecarrier: 'Delta Dental',
    offices: 'Westside Family Dental',
    patientname: 'Lisa Anderson',
    paidamount: 280,
    claimstatus: 'Processing',
    typeofinteraction: 'X-Ray',
    patientdob: '1990-12-18',
    dos: '2024-01-14',
    productivityamount: 280,
    missingdocsorinformation: '',
    howweproceeded: 'Submitted for review',
    escalatedto: '',
    commentsreasons: 'Diagnostic imaging for treatment planning',
    emailaddress: 'lisa.anderson@email.com',
    status: 'In Progress',
    timestampbyinteraction: '2024-01-16T09:15:00Z'
  },
  {
    timestamp: '2024-01-16T10:45:00Z',
    insurancecarrier: 'BlueCross BlueShield',
    offices: 'North Park Dental',
    patientname: 'David Martinez',
    paidamount: 1500,
    claimstatus: 'Paid',
    typeofinteraction: 'Bridge Installation',
    patientdob: '1975-05-22',
    dos: '2024-01-09',
    productivityamount: 1500,
    missingdocsorinformation: '',
    howweproceeded: 'Pre-authorized and processed',
    escalatedto: '',
    commentsreasons: '3-unit bridge, excellent fit',
    emailaddress: 'david.martinez@email.com',
    status: 'Completed',
    timestampbyinteraction: '2024-01-16T10:45:00Z'
  },
  {
    timestamp: '2024-01-16T13:20:00Z',
    insurancecarrier: 'Humana',
    offices: 'Downtown Dental Center',
    patientname: 'Jennifer Taylor',
    paidamount: 0,
    claimstatus: 'Pending',
    typeofinteraction: 'Consultation',
    patientdob: '1983-08-07',
    dos: '2024-01-15',
    productivityamount: 200,
    missingdocsorinformation: 'Treatment plan required',
    howweproceeded: 'Preparing detailed treatment plan',
    escalatedto: 'Treatment Coordinator',
    commentsreasons: 'Complex case requiring multiple procedures',
    emailaddress: 'jennifer.taylor@email.com',
    status: 'Planning',
    timestampbyinteraction: '2024-01-16T13:20:00Z'
  },
  {
    timestamp: '2024-01-16T14:55:00Z',
    insurancecarrier: 'Aetna',
    offices: 'Eastside Dental',
    patientname: 'Christopher Lee',
    paidamount: 750,
    claimstatus: 'Paid',
    typeofinteraction: 'Extraction',
    patientdob: '1965-01-25',
    dos: '2024-01-12',
    productivityamount: 750,
    missingdocsorinformation: '',
    howweproceeded: 'Standard surgical claim',
    escalatedto: '',
    commentsreasons: 'Wisdom tooth extraction, no complications',
    emailaddress: 'chris.lee@email.com',
    status: 'Completed',
    timestampbyinteraction: '2024-01-16T14:55:00Z'
  },
  {
    timestamp: '2024-01-17T08:30:00Z',
    insurancecarrier: 'Guardian',
    offices: 'Westside Family Dental',
    patientname: 'Amanda Rodriguez',
    paidamount: 420,
    claimstatus: 'Paid',
    typeofinteraction: 'Periodontal Treatment',
    patientdob: '1987-04-16',
    dos: '2024-01-14',
    productivityamount: 420,
    missingdocsorinformation: '',
    howweproceeded: 'Electronic submission with documentation',
    escalatedto: '',
    commentsreasons: 'Scaling and root planing completed',
    emailaddress: 'amanda.rodriguez@email.com',
    status: 'Completed',
    timestampbyinteraction: '2024-01-17T08:30:00Z'
  },
  {
    timestamp: '2024-01-17T11:00:00Z',
    insurancecarrier: 'Cigna',
    offices: 'North Park Dental',
    patientname: 'Kevin Thompson',
    paidamount: 0,
    claimstatus: 'Rejected',
    typeofinteraction: 'Implant Consultation',
    patientdob: '1980-10-12',
    dos: '2024-01-16',
    productivityamount: 150,
    missingdocsorinformation: 'Medical necessity documentation',
    howweproceeded: 'Gathering additional documentation',
    escalatedto: 'Clinical Director',
    commentsreasons: 'Need to establish medical necessity',
    emailaddress: 'kevin.thompson@email.com',
    status: 'Documentation',
    timestampbyinteraction: '2024-01-17T11:00:00Z'
  },
  {
    timestamp: '2024-01-17T15:25:00Z',
    insurancecarrier: 'MetLife',
    offices: 'Downtown Dental Center',
    patientname: 'Michelle White',
    paidamount: 890,
    claimstatus: 'Paid',
    typeofinteraction: 'Orthodontic Adjustment',
    patientdob: '2005-06-30',
    dos: '2024-01-15',
    productivityamount: 890,
    missingdocsorinformation: '',
    howweproceeded: 'Monthly orthodontic claim',
    escalatedto: '',
    commentsreasons: 'Regular adjustment, treatment progressing well',
    emailaddress: 'michelle.white@email.com',
    status: 'Completed',
    timestampbyinteraction: '2024-01-17T15:25:00Z'
  },
  // Additional entries to reach substantial dataset
  ...Array.from({ length: 20 }, (_, i) => ({
    timestamp: `2024-01-${String(18 + (i % 10)).padStart(2, '0')}T${String(9 + (i % 8)).padStart(2, '0')}:${String((i * 15) % 60).padStart(2, '0')}:00Z`,
    insurancecarrier: ['Delta Dental', 'BlueCross BlueShield', 'Aetna', 'Cigna', 'MetLife', 'Humana', 'Guardian'][i % 7],
    offices: ['Downtown Dental Center', 'Westside Family Dental', 'North Park Dental', 'Eastside Dental'][i % 4],
    patientname: [
      'Mark Johnson', 'Susan Miller', 'James Wilson', 'Patricia Garcia',
      'Richard Martinez', 'Linda Anderson', 'Charles Taylor', 'Barbara Thomas',
      'Daniel Jackson', 'Nancy White', 'Matthew Harris', 'Karen Martin',
      'Anthony Thompson', 'Betty Moore', 'Donald Clark', 'Helen Rodriguez',
      'Paul Lewis', 'Sandra Walker', 'Steven Hall', 'Donna Allen'
    ][i],
    paidamount: [300, 450, 600, 750, 900, 1200, 0, 350, 500, 800][i % 10],
    claimstatus: ['Paid', 'Pending', 'Processing', 'Denied', 'Rejected'][i % 5],
    typeofinteraction: [
      'Cleaning', 'Filling', 'Crown', 'Root Canal', 'Extraction',
      'X-Ray', 'Consultation', 'Orthodontic', 'Whitening', 'Emergency'
    ][i % 10],
    patientdob: `19${70 + (i % 40)}-${String((i % 12) + 1).padStart(2, '0')}-${String((i % 28) + 1).padStart(2, '0')}`,
    dos: `2024-01-${String(10 + (i % 15)).padStart(2, '0')}`,
    productivityamount: [300, 450, 600, 750, 900, 1200, 0, 350, 500, 800][i % 10],
    missingdocsorinformation: i % 7 === 0 ? 'Documentation pending' : '',
    howweproceeded: i % 4 === 0 ? 'Follow-up required' : 'Standard processing',
    escalatedto: i % 8 === 0 ? 'Supervisor' : '',
    commentsreasons: `Standard ${['Cleaning', 'Filling', 'Crown', 'Root Canal', 'Extraction'][i % 5]} procedure`,
    emailaddress: `patient${i + 13}@email.com`,
    status: ['Completed', 'In Progress', 'Planning', 'Appeal', 'Documentation'][i % 5],
    timestampbyinteraction: `2024-01-${String(18 + (i % 10)).padStart(2, '0')}T${String(9 + (i % 8)).padStart(2, '0')}:${String((i * 15) % 60).padStart(2, '0')}:00Z`
  }))
]

// Mock filter options
export const mockFilterOptions = {
  offices: [
    { value: 'Downtown Dental Center', label: 'Downtown Dental Center', count: 8 },
    { value: 'Westside Family Dental', label: 'Westside Family Dental', count: 7 },
    { value: 'North Park Dental', label: 'North Park Dental', count: 6 },
    { value: 'Eastside Dental', label: 'Eastside Dental', count: 5 },
  ],
  insuranceCarriers: [
    { value: 'Delta Dental', label: 'Delta Dental', count: 6 },
    { value: 'BlueCross BlueShield', label: 'BlueCross BlueShield', count: 5 },
    { value: 'Aetna', label: 'Aetna', count: 4 },
    { value: 'Cigna', label: 'Cigna', count: 4 },
    { value: 'MetLife', label: 'MetLife', count: 3 },
    { value: 'Humana', label: 'Humana', count: 2 },
    { value: 'Guardian', label: 'Guardian', count: 2 },
  ],
  claimStatus: [
    { value: 'Paid', label: 'Paid', count: 18 },
    { value: 'Pending', label: 'Pending', count: 6 },
    { value: 'Processing', label: 'Processing', count: 4 },
    { value: 'Denied', label: 'Denied', count: 3 },
    { value: 'Rejected', label: 'Rejected', count: 1 },
  ],
  interactionTypes: [
    { value: 'Cleaning', label: 'Cleaning', count: 4 },
    { value: 'Filling', label: 'Filling', count: 3 },
    { value: 'Crown Placement', label: 'Crown Placement', count: 2 },
    { value: 'Root Canal', label: 'Root Canal', count: 2 },
    { value: 'Extraction', label: 'Extraction', count: 2 },
    { value: 'X-Ray', label: 'X-Ray', count: 2 },
    { value: 'Consultation', label: 'Consultation', count: 2 },
    { value: 'Bridge Installation', label: 'Bridge Installation', count: 1 },
    { value: 'Whitening Treatment', label: 'Whitening Treatment', count: 1 },
    { value: 'Periodontal Treatment', label: 'Periodontal Treatment', count: 1 },
    { value: 'Implant Consultation', label: 'Implant Consultation', count: 1 },
    { value: 'Orthodontic Adjustment', label: 'Orthodontic Adjustment', count: 1 },
  ],
}
